apiVersion: v1
kind: Pod
metadata:
  name: configs-provisioner
spec:
  volumes:
    - name: grafana-claim0
      persistentVolumeClaim:
        claimName: grafana-claim0
    - name: prometheus-claim0
      persistentVolumeClaim:
        claimName: prometheus-claim0
  containers:
    - name: ubuntu
      image: ubuntu:latest
      # Just sleep forever
      command: [ "sleep" ]
      args: [ "infinity" ]
      volumeMounts:
        - mountPath: "/grafana-claim0"
          name: grafana-claim0
        - mountPath: "/prometheus-claim0"
          name: prometheus-claim0
